---
vault:
  image: "quay.io/samsung_cnct/vault"
  imageTag: "0.8.3"
  imagePullPolicy: "Always"
  component: "vault"
  listenerAddress: "127.0.0.1"
  listenerPort: 8200
# useRedirectAddr: false
  redirectAddr: "vault-vault.vault-staging"
  clusterAddress: "vault-vault.vault-staging"
  redirectPort: 8200
# Valid choices are [etcd, consul, inmem]
  backend: "etcd"
  enableTLS: false
  enableDebug: true
  replicas: 3
  cpu: "512m"
  memory: "200Mi"

# Consul backend example
  consulBackend:
    address: "consul-consul:8500"
    token: "token"

# etcd backend example
  etcdBackend:
    discoverySRV:
    address: "vault-etcd-vault-etcd.vault-etcd-staging"
    port: 3379
    etcdApi: "v3"
    path: "vault/"
    sync: "false"
    username: ""
    password: ""
    scheme: "http"
    token: "token"
    disableClustering: "false"
    clientCA:
    clientCert:
    clientKey:

  init:
    skip_init_vault: true
    skip_unseal_vault: true
    skip_email_recipients: true
    enable_auth_backends: true
    encrypt_key_to_rcpt: false
    recipients:
      - email: ""
        pubkey: ""
      - email: ""
        pubkey: ""
      - email: ""
        pubkey: ""
    auth_backends:
      - github
      - kubernetes
      - aws
      - approle

# TLS info
  tls:
    cert: ""
    key: ""
    ca: ""

  tolerations:
   # - key: taintKey
   #   value: taintValue
   #   operator: Equal
   #   effect: NoSchedule
  scheduling:
    affinity:
      node:
        type: #requiredDuringSchedulingIgnoredDuringExecution
        labels:
        # - key: iamalabelkey
        #   operator: In
        #   values: ["value1", "value2"]

