---
clusterDomain: cluster.local
vault:
  image: quay.io/samsung_cnct/vault
  imageTag: v0.9.3
  imagePullPolicy: "Always"
  listenerPort: 8200
  clusterListenerPort: 8201
# Valid choices are [etcd, inmem]
  backend: "etcd"
  enableDebug: false
  replicas: 3
  secretShares: 5
  unsealShares: 3
  initBackoff: 10
  initDeadline: 180
  pgpKeys:
  rootPgpKey: 
  cpu: "500m"
  memory: "200Mi"
  # init and unseal vault as it comes up. Store unseal keys and root token in a secret
  setup: 
    init: false
    unseal: false
    masterSecret: 
# etcd
  etcdSetupEnabled: false
  etcdBackend:
    discoverySRV:
    address: "vault-etcd-vault-etcd.vault-etcd-staging"
    port: 3379
    etcdApi: "v3"
    path:
    sync: "false"
    username: ""
    password: ""
    disableClustering: "false"
    tls:
      enabled: false
      secret:
        mountPath: /etc/etcd/tls
        name:
        certFile:
        keyFile:
        caFile:
# TLS info
  tls:
    enabled: false
    secret:
      name: vault-client-tls
      mountPath: /etc/vault/tls
      certFile: ca.pem
      keyFile: vault-client.pem
      caFile: vault-client-key.pem
  tolerations:
   # - key: taintKey
   #   value: taintValue
   #   operator: Equal
   #   effect: NoSchedule
  scheduling:
    affinity:
      node:
        type: #requiredDuringSchedulingIgnoredDuringExecution
        labels:
        # - key: iamalabelkey
        #   operator: In
        #   values: ["value1", "value2"]
